- id: format
  name: Format project using `xmake format`
  description: This hook formats the entire project, using the same formatter that `xmake` uses.
  entry: format
  language: python
  stages: [pre-commit, pre-merge-commit, manual]
  pass_filenames: false
- id: check
  name: Check the project using `xmake check`
  description: This hook checks the entire project, using the checkers from `xmake` specified as arguments.
  entry: check
  language: python
  stages: [pre-commit, pre-merge-commit, manual]
  pass_filenames: false
